version: '3.4'
services:
  db:
    image: postgres:12.7-alpine
    restart: always
    hostname: db
    container_name: indonesia-db
    env_file: 
      - .env
    ports:
      - 5432:5432
    volumes:
      - dev_ind_db_data:/var/lib/postgresql/data
    networks:
      - backend
networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: indonesia_infra
volumes:
  dev_ind_db_data: {}